### ISSUE TITLE
Popup dismissed when a hyphen is entered

### ISSUE THREAD

**Issue by lassebm** [ksuther/KSImageNamed-Xcode#1]
Title says it all. Thanks for a great plug-in!

**Comment by Mark2xv** [comment]
Is there any chance this might be added? This seems like a very useful plugin but completely unusable for us at the moment, as we use a lot of hyphens. 
We often use "SizeType-ImageName-Color.png" typed image names, like "L-UserCircle-WHITE.png".

**Comment by ksuther** [comment]
I don't have any plans to attempt this, unfortunately. PRs welcome, obviously, but it won't be coming from me any time soon.
