### ISSUE TITLE
TextView doesn't reassess width for longer filenames

### ISSUE THREAD

**Issue by neilkachu** [ksuther/KSImageNamed-Xcode#12]
If your initial visible list of images have short names, all subsequent filenames are truncated to the width set by these even though the popup window has space to display them fully.

(This only occurs when scrolling the list, using the autocomplete corrects the field width) 

![Screen Shot 2013-02-07 at 09 09 14](https://f.cloud.github.com/assets/476062/134980/6291f272-7106-11e2-8ea8-f98d76ef5c2a.png)

**Comment by ksuther** [comment]
This doesn't seem to be a problem on Xcode 7 anymore.
