### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [ksuther/KSImageNamed-Xcode#43]
I love this plugin. Can you please make it support Swift as well?

**Comment by camina-apps** [comment]
+1  would love to see a new version with swift support in alcatraz

**Comment by rishabhtayal** [comment]
+1

**Comment by bumaociyuan** [comment]
+1

**Comment by LengBinBin** [comment]
+1

**Comment by nextriot** [comment]
+1

**Comment by mdagostino** [comment]
+1

**Comment by zendobk** [comment]
+1, great plugin

**Comment by kaunteya** [comment]
+1

**Comment by VonFry** [comment]
+1

**Comment by daniel-shin1104** [comment]
+1

**Comment by dev-xdyang** [comment]
+1

**Comment by hasankacar** [comment]
+1

**Comment by czboosj** [comment]
+1

**Comment by czboosj** [comment]
+1

**Comment by culmek** [comment]
+1

**Comment by orkenstein** [comment]
+100500

**Comment by kapoorsahil** [comment]
+1

**Comment by maxmadell** [comment]
+1

**Comment by tidane** [comment]
+1

**Comment by mayur43s** [comment]
+1

**Comment by xinnyu** [comment]
+1

**Comment by kohdesmond** [comment]
+1

**Comment by loveforgeter** [comment]
+1

**Comment by ksuther** [comment]
42b71680f8bdae406a7d027bbfd7221d63c48980 adds experimental Swift support. Please let me know if there are any issues.

**Comment by zendobk** [comment]
sounds good, thanks you!

**Comment by frogcjn** [comment]
Should be more Swift way: 

The init method should be UIImage(named:"imagename")
less people would use UIImage.init(named:"imagename")

**Comment by perzect** [comment]
+1,Very want to see UIImage(named:"imagename") replace UIImage.init(named:"imageName")

**Comment by ksuther** [comment]
@frogcjn, @perzect: Give it a shot with cf4377c6f14bf6793248f61b2d8dc7a7c2c14b83.

**Comment by frogcjn** [comment]
@ksuther Thanks a lot! It just works.
