### ISSUE TITLE
Doesnt recognise when Im entering not image name

### ISSUE THREAD

**Issue by ivan-golub** [ksuther/KSImageNamed-Xcode#48]
Would be good if plagin could recognise that Im entering not an image name, but function.
Example: when Im entering
[imageView setImage:[UIImage imageNamed:[NSString stringWithFormat:@"my_image_%i", imageIndex]]];

In such cases plugin just goes crazy and trying to find images with name "[NSString ..." and hides autocompletion. Plugin should only triggers when input starts with @"

**Comment by ksuther** [comment]
Autocomplete triggering after the colon is entered is on purpose, as it ensures that you can autocomplete after typing imageNam<autocomplete>. If the completion suggestions only triggered after a @" then it would block the primary way of showing the completions menu.
