### ISSUE TITLE
framework not found CoreImage for architecture x86_64

### ISSUE THREAD

**Issue by xiliyue** [ksuther/KSImageNamed-Xcode#50]
When i building this project in Xcode, i got following issue
ld: warning: ObjC object file (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/CoreService.framework/CoreService) was compiled for iOS Simulator, but linking for MacOSX
ld: framework not found CoreImage for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

environment
Xcode 6.2   OS X 10.10.2

**Comment by ksuther** [comment]
Sounds like your SDK or build paths aren't correct.
