### ISSUE TITLE
Unable to autocomplete string other than image name

### ISSUE THREAD

**Issue by cjwhitsitt** [ksuther/KSImageNamed-Xcode#52]
If you try to enter a variable name instead of a string literal (eg, kMyStringDefinition or self.anotherString), autocomplete does not work. 

Is it possible to limit this to only autocomplete image names if the @ is entered? This would differentiate between string literals for image assets or variable names.

**Comment by ksuther** [comment]
Limiting it to just @" makes it so autocomplete can't work when pressing return after selecting imageNamed: from the autocomplete list. The new way I'm handling completion suggestions make it possible to add an option to include both images and variables together though.
