### ISSUE TITLE
cant install KSImageNamed by Alcatraz

### ISSUE THREAD

**Issue by huangqiaobo** [ksuther/KSImageNamed-Xcode#59]
KSImageNamed crashed in Xcode Version 7.0 (7A220)
So I skip it when i open Xcode.
Then i opened Alcatraz,remove the KSImageNamed and reinstall it, then i found that it cant be install in Xcode Version 7.0 (7A220)

**Comment by calios** [comment]
Same issue occured to me. Xcode 7.0.1. Failed to reinstall it by Alcatraz. 
@ksuther Thanks for checking it.

**Comment by ksuther** [comment]
This usually happens when there are two versions of KSImageNamed installed at once. Make sure the old one is removed before installing it again.

**Comment by Jacob-LJ** [comment]
how to make sure the old one is removed before installing it again, please.

**Comment by ksuther** [comment]
Instructions are in the read me:

Important: Old versions of KSImageNamed were installed in ~/Library/Developer/Application Support/Developer/Shared/Xcode/Plug-ins. Make sure to remove KSImageNamed.xcplugin from there before installing the new one.
