### ISSUE TITLE
Plugin installing to wrong directory via Alcatraz

### ISSUE THREAD

**Issue by nextriot** [ksuther/KSImageNamed-Xcode#60]
Hi:

I'm using `Xcode Version 7.0 (7A218)` on `OS X Version 10.11 (15A282b)`.

When I use package manager to install this plugin it gets copied to the following directory: `/Users/[HOME]/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin`

The directory for Xcode plugins, for at least a year now seems to have been changed to: `/Users/[HOME]/Library/Application Support/Developer/Shared/Xcode/Plug-ins`

Furthermore, even if I simply drag and drop the plugin from one folder to the other it doesn't get recognised. Also, package manager (Alcatraz) never reports the plugin as `installed` in its GUI.

Any ideas?

**Comment by ksuther** [comment]
The first path in ~/Library/Developer is correct. KSImageNamed uses a completion strategy with requires the ideplugin suffix and has to be in that location. Putting it in Application Support will prevent Xcode from loading it.

**Comment by nextriot** [comment]
I get what you're saying, but at least in my case that doesn't seem to be correct. All my working plugins - and ones recognised by Alcatraz - are in the second directory. The fact that KSImageNamed doesn't go there by default may be what's causing the issues I'm seeing.

Is there anything in the plugin that I can change, whether a line from the source code, or an entry in the .plist that I can amend to account for the altered directory - assuming there is something in the plugin that is dependent on the location being static? As per your comment:

> KSImageNamed uses a completion strategy with requires the ideplugin suffix and has to be in that location. Putting it in Application Support will prevent Xcode from loading it.

**Comment by ksuther** [comment]
You can put KSImageNamed.ideplugin anywhere, there's nothing in the bundle that is dependent on the path. You can move it to the Application Support Plug-ins directory and see if it works for you, but in my experience ideplugins don't get loaded there.

**Comment by nextriot** [comment]
Thanks for the swift reply Kent. Sounds good. I'll give it some more experimenting & let you know if I resolve anything. Thanks for your time.
