### ISSUE TITLE
Cann't install successfully

### ISSUE THREAD

**Issue by cctvzxxz1** [ksuther/KSImageNamed-Xcode#61]
I failed to use Alcatraz to install KSImageNamed-Xcode, and I also failed to use the following method to install.

Build the KSImageNamed target in the Xcode project and the plug-in will automatically be installed in ~/Library/Developer/Xcode/Plug-ins. Relaunch Xcode and imageNamed: will magically start autocompleting your images.

**Comment by renjingkai** [comment]
When i ran in Xcode 6.4 ,i had this problem too! Here is my solution as follow:
1.打开xcode插件所在的目录：
~/{当前用户名}/Library/Developer/Xcode/Plug-ins
2.选择已经安装的插件例如VVDocument，右键点击show package contents，
3.找到info.plist 文件，找到DVTPlugInCompatibilityUUIDs的项目，
4.添加C4A681B0-4A26-480E-93EC-1218098B9AA0（当前xcode的一个号码），这个号码怎么得到？
 在终端执行 defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID 即可
5.再右键“打开报内容”双击contents\MacOS目录下的一个黑色图标，会打开终端窗口，最后打印“进程已完成”之类，
重启xcode

**Comment by homekuanyi** [comment]
i had this problem,  i sovled it by typing the command below: 

open ~/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin/Contents/MacOS/KSImageNamed

then, close the terms, and restart xcode.

**Comment by cctvzxxz1** [comment]
@renjingkai  Thank you, I solved this problem by using your method.
@homekuanyi  I tried your method,but it did not work.
