### ISSUE TITLE
Xcode 7.1 issues

### ISSUE THREAD

**Issue by jcarroll3** [ksuther/KSImageNamed-Xcode#63]
Seemed to work alright in 7.0.1, 7.1 cant even install

**Comment by homekuanyi** [comment]
after KSImageNamed's installation, try this command in terms: 

open ~/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin/Contents/MacOS/KSImageNamed

then, close the terms, and restart xcode. it works for me.

**Comment by jcarroll3** [comment]
thanks

**Comment by wyd2004** [comment]
it works! Thanks!

**Comment by rickytribbia** [comment]
It works! Thank you. 
It will be better if it will be installable by Alcatraz as usual, but for now it's ok. 
Great work, guys..

**Comment by ksuther** [comment]
I've submitted a PR to Alcatraz that will fix installing with it: https://github.com/supermarin/Alcatraz/pull/369
