### ISSUE TITLE
cannot install from Alcatraz

### ISSUE THREAD

**Issue by 7934345** [ksuther/KSImageNamed-Xcode#64]
Xcode 7.1
in package manager search KSImageNamed and click install, wait for a while it rolls back.

**Comment by chencrstu** [comment]
you can download source , build and move KSImageNamed.ideplugin into ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins

**Comment by ozygod** [comment]
I did it，and restart Xcode，but nothing happen..

**Comment by ksuther** [comment]
This is a problem with Alcatraz not supporting ideplugins. I've submitted a PR to Alcatraz.

https://github.com/supermarin/Alcatraz/pull/369
