### ISSUE TITLE
Xcode 7.1  cannot  install

### ISSUE THREAD

**Issue by VVJason** [ksuther/KSImageNamed-Xcode#65]
Xcode 7.1  cannot  install，the Same as with Alcatraz

**Comment by alem0lars** [comment]
:+1:

**Comment by ksuther** [comment]
Is KSImageNamed.ideplugin appearing in ~/Library/Developer/Xcode/Plug-ins? If so, did you get the bundle load warning when you first relaunched Xcode? If not, try moving it out of that folder, quit and relaunch Xcode, then move it back in and try quitting and relaunching again.

**Comment by ksuther** [comment]
I've submitted a PR to Alcatraz that will fix not being able to install it from Alcatraz.

https://github.com/supermarin/Alcatraz/pull/369
