### ISSUE TITLE
xcode6.4 can't use

### ISSUE THREAD

**Issue by codwam** [ksuther/KSImageNamed-Xcode#66]
KSImageNamed plug-in will automatically be installed in ~/Library/Developer/Xcode/Plug-ins,
not in ~/Library/Developer/Application Support/Developer/Shared/Xcode/Plug-ins

I have xcode6.4 and xcode7.1.1
xcode7 can user but xcode6 can't ?

**Comment by ksuther** [comment]
You can try adding the Xcode 6.4 UUID to the Info.plist, but I haven't verified that this plugin works on Xcode 6 anymore. It is developed exclusively for Xcode 7.

**Comment by codwam** [comment]
Xcode 6.4 UUID ( 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 ) add to ~/Library/Developer/Xcode/Plug-ins/KSImageNamed.ideplugin ( info.plist ) is OK！！！

But I hope you can make a new branch for xcode6 if KSImageNamed.ideplugin and KSImageNamed.xcplugin can work together...

**Comment by ksuther** [comment]
Good to know it works, I've readded the Xcode 6.4 UUID to the Info.plist. Thanks!
