### ISSUE TITLE
Why the Plug-in can't be install after I build the project?

### ISSUE THREAD

**Issue by Story5** [ksuther/KSImageNamed-Xcode#68]
I downloaded the project and builded it successfuly.Then I restart the Xcode,but I can't use it and there is no related file under the directory ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins.
I appreciate for your help!

**Comment by ksuther** [comment]
It is installed in ~/Library/Developer/Xcode/Plug-in.

**Comment by tangqi92** [comment]
@ksuther It did installed in ~/Library/Developer/Xcode/Plug-ins. But after I restart the Xcode, I still can't use it. The other plugins that are installed in ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins can be normal use.( My Xcode is 7.1.1, OS X 10.11.1)

**Comment by ksuther** [comment]
Take a look at some of the other closed issues in this project, some other people have run into this as well. I'm not sure what's happening, Xcode should load all ideplugins from ~/Library/Developer/Plug-ins. Also, make sure you don't have an old version of KSImageNamed.xcplugin installed in ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins.

**Comment by Story5** [comment]
I have solved the problem,and the plug-in unit does work now.It helps me to input the image name in Xcode project more effectively.Thank you for your help and works!
