### ISSUE TITLE
xcode7.1.1 can’t autocomplete with obj name

### ISSUE THREAD

**Issue by ysk666666** [ksuther/KSImageNamed-Xcode#72]
xcode7.1.1 can’t autocomplete with obj name
eg:
NSString * textImageName = [NSString stringWithFormat:@"startTextImage-%d",i];
textImageView.image = [UIImage imageNamed:textImageName];

it can not autocomplete with "textImageName"

3Q

**Comment by ksuther** [comment]
This is intentional, this plugin replaces the autocomplete suggestions for imageNamed: with the images found in the workspace. It won't combine suggestions for variable names.
