### ISSUE TITLE
xcode 7.2 安装后不起作用

### ISSUE THREAD

**Issue by LargeShrimp** [ksuther/KSImageNamed-Xcode#73]
安装路径是~/Library/Developer/Xcode/Plug-ins
但是其他的插件都是在
~/Library/Application Support/Developer/Shared/Xcode/Plug-ins

copy 过去后就可以了

**Comment by lixiwen** [comment]
我的Xcode版本也是7.2，但是为什么没有
~/Library/Application Support/Developer/Shared/Xcode/Plug-ins
这个路径，进到Application Support里边以后，就没有Developer这个路径了

**Comment by bigParis** [comment]
把XCode完全退出,再终端defaults write com.apple.dt.Xcode KSShowExtensionInImageCompletion -bool YES
