### ISSUE TITLE
Support namespace

### ISSUE THREAD

**Issue by mazllia** [ksuther/KSImageNamed-Xcode#77]
Huge thanks to this project saving me tons of time. Would be even better to support namespaces :+1: 

> Autocompletion only shows the image name without namespace prefix when namespaces enabled.
![2016-01-06 3 23 29](https://cloud.githubusercontent.com/assets/3256177/12137277/02aca1e8-b48a-11e5-934f-12578721081b.png)

**Comment by ksuther** [comment]
Thanks for the suggestion! Please give the latest changes a try.
