### ISSUE TITLE
crash in playground

### ISSUE THREAD

**Issue by coldmn3** [ksuther/KSImageNamed-Xcode#79]
Hi,I reproduced the crash in [#78](https://github.com/ksuther/KSImageNamed-Xcode/issues/78). I cant reopen the issue, so I opened a new one.
[crash_log.txt](https://github.com/ksuther/KSImageNamed-Xcode/files/111620/crash_log.txt)

**Comment by ksuther** [comment]
Thank you! Can you also attach a playground where it happens (indicate where you're adding the semicolon)? I can't reproduce it in a blank playground, but I see the crash in the log.

**Comment by coldmn3** [comment]
I found out when I created a new playground,it didn't crash, may be it's playground's bug?
[MyPlayground.playground.zip](https://github.com/ksuther/KSImageNamed-Xcode/files/114935/MyPlayground.playground.zip)

**Comment by ksuther** [comment]
commit:4e89bb6636bad8c9bb76ee33d64acc52be5239c9 may fix this, can you try that?

**Comment by coldmn3** [comment]
Yes,it's fixed! Thank you very much.
