### ISSUE TITLE
A little suggestion

### ISSUE THREAD

**Issue by fyt10060** [ksuther/KSImageNamed-Xcode#81]
sometimes，I can't get the image from my designer immediately, so I just create an  imageset with a name but without image, but when I want to reach this image quickly, I notice that you plugin are not able to display the imagesets which are empty, so I was wandering can you make a small change that also show the image sets which are empty?

**Comment by ksuther** [comment]
I would suggest reverting d384aac03122bd9934b7845a8396a2bcbf106871 in a local branch if you want to allow empty imagesets.

**Comment by fyt10060** [comment]
Thanks a lot, that's very helpful!
