### ISSUE TITLE
About Xcode 8.0

### ISSUE THREAD

**Issue by zhichao8888** [ksuther/KSImageNamed-Xcode#84]
When I add UUID to KSImageNamed-Xcode info.plist ,then I open Xcode 8.0 to edit, but the Xcode crushes immediately.

**Comment by ioshuihui** [comment]
So do I

**Comment by ksuther** [comment]
I haven't yet tried running Xcode 8 with plugins, if I do I'll investigate this further. Otherwise pull requests are welcome.

**Comment by xunan623** [comment]
so do i

**Comment by BrotherXu2015555** [comment]
me too

**Comment by ygit** [comment]
is there any KSImage will work on Xcode 8 @ksuther ?

**Comment by ygit** [comment]
is there any way KSImage will work on Xcode 8 @ksuther ?

**Comment by AMEstudio** [comment]
i have use this 
https://github.com/fpg1503/MakeXcodeGr8Again 
make the Xcode8 to XcodeGr8 and i add the uuid to plugins
but the KSImage also not work
so sad :(
@ksuther

**Comment by LicoC** [comment]
so do I, when I entered "UI", xcode8 crashed. And after I removed KSImageNamed from plugs-in document, xcode works fine

**Comment by tonysky** [comment]
So do I. When I entered any letter, Xcode8 crashed.

**Comment by ksuther** [comment]
Again, this won't change if nobody gives a reproduction project and steps.

**Comment by tonysky** [comment]
And how to operate?
