### ISSUE TITLE
Will it support Xcode 8?

### ISSUE THREAD

**Issue by manuqiao** [ksuther/KSImageNamed-Xcode#95]
Hello, I'm currently using Xcode 8.3. I compiled the project and reopened Xcode. But Xcode crashes every time it prompts auto completion.

**Comment by ksuther** [comment]
Did you unsign Xcode?

**Comment by libiao88** [comment]
i've got the same issue

**Comment by ksuther** [comment]
You likely have no unsigned Xcode (see https://github.com/fpg1503/MakeXcodeGr8Again).
